baseURL: https://thaisiri-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Thaisiri Siripoorikan
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    #subtitle: |-
      #A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      #AND RELEASED UNDER THE CREATIVE COMMONS.
    title: I am Thaisiri Siripoorikan and this is my website!
  blog: {}
  contact:
    address:
      - city: London, W2 1DB
        country: United Kingdom
        street: Edgware Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: thaisiris.mba2024@london.edu
        title: Email
    enable: yes
    phone:
      - phone: 0777-8060383
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    #copyright: LBS
    enable: yes
    #quicklinks:
      #- alt: HTML5 UP
        #text: 'Design: '
        #rl: https://www.html5up.net
    social:
      #- icon: fa-twitter
        #label: Twitter
        #url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/thaisiri.siripoorikan/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/thaisiri
      - icon: fa-github
        label: GitHub
        url: https://github.com/thaisiri/
      #- icon: fa-linkedin
        #label: LinkedIn
        #url: https://www.linkedin.com
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      #- name: Generic Blog
        #url: blogs/ipsum
      #- name: Elements
        #surl: elements.html
    menu: Menu
    #subtitle: By HTML5 Up
    title: My website
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        #subtitle: Ipsum Dolor Sit Amet
        title: Risk-Return of DJIA stocks
        url: blogs/risk_return
      - image: profile.jpg
        subtitle: My info
        title: My info
        url: blogs/tempus
      - image: uk.jpg
        #subtitle: Lorem Etiam Nullam
        title: Money in UK politics
        url: blogs/homework3
      #- image: pic04.jpg
       # subtitle: Nisl Sed Aliquam
        #title: Ipsum
        #url: blogs/ipsum
      #- image: pic05.jpg
       # subtitle: Ipsum Dolor Sit Amet
        #title: Consequat
        #url: blogs/ipsum
      #- image: pic06.jpg
       # subtitle: Feugiat Amet Tempus
        #title: Etiam
        #url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Hi, My name is Thaisiri Siripoorikan. Currently, I am studying an MBA program at LBS(London Business School). Prior to the MBA, I have been working at PTT, which is one of the largest energy company in Thailand!"
    title: Get to know me!
    url: blogs
